cloudsql_project              = "ent-kakka-dev"
pubsub_project                = "ent-kakka-dev"
storage_project               = "ent-kakka-dev"
kingu_pub_sub_project         = "ent-kingu-dev"
nabu_job_event_pubsub_project = "ent-nabu-dev"
service_account               = "serviceAccount:application@ent-kakka-dev.iam.gserviceaccount.com"
kingu_storage_bucket          = "ror-kingu-dev"
bucket_instance_suffix        = "dev"
