env: dev

replicas: 1


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

sql:
  instance: carbon-1287:europe-west1:kakka-db-1=tcp:5432

configMap:
  gcsBlobstore: marduk
  projectId: carbon-1287
  pelias:
    gtfs: true
    placeBoost: 40
    boostConfig: {"defaultValue":30, "stopTypeFactors":{"airport":{"*":2},"busStation":{"*":2},"metroStation":{"*":2},"railStation":{"*":2}},"interchangeFactors":{"recommendedInterchange":2,"preferredInterchange":5}}
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10



resources:
  cpuLimit: 2500m
  memLimit: 6000Mi
  cpuRequest: "1"
  memRequest: 4500Mi
  xmx: 4g

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-carbon-storage-key
    readOnly: true
  - name: kakka-service-account
    mountPath: /etc/kakka-service-account
    subPath: ""
    secretName: kakka-service-account
    readOnly: true
  - name: marduk-pubsub-key
    mountPath: /etc/marduk-pubsub-account
    subPath: ""
    secretName: marduk-pubsub-key
    readOnly: true


configMapMounts:
  - name: application-config
    mountPath: /etc/application-config
    subPath: ""
    configMap: kakka-config
    readOnly: false

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8776
  httpAdmin:
    externalPort: 8080
    internalPort: 8080
  jolokia:
    internalPort: 8778

ingress:
    enabled: true
    devIp: 35.195.223.29
    stagingIp: 35.195.146.93
    productionIp: 35.187.15.14
