replicas: 2

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  cpuLimit: "3"
  memLimit: 12000Mi
  cpuRequest: "2"
  memRequest: 8500Mi
  xmx: 12g

secretMount:
  name: kakka-key
  mountPath: /etc/kakka/credentials.json
  subPath: credentials.json
  secretName: ror-kakka-sa-key
  readOnly: true

configMapMount:
  name: kakka-config
  tiamatExportName: kakka-tiamat-export-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8776
  httpAdmin:
    externalPort: 8080
    internalPort: 8080

cronjobTiamatExportStatus:
  enabled: true
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  resources:
    cpuLimit: 900m
    memLimit: 2550Mi
    cpuRequest: 100m
    memRequest: 1000m
  image:
    repo: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.10

secrets:
  ror-kakka-secrets:
    - SPRING_DATASOURCE_PASSWORD
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKKA_CLIENT_SECRET
    - SLACK_URL
