apiVersion: v1
data:
  application.properties: |-
    tiamat.poi.update.enabled={{ .Values.configMap.poiUpdateEnabled }}
    tiamat.url=http4://tiamat:80
    spring.datasource.driver-class-name=org.postgresql.Driver
    organisations.api.url=http://baba/services/organisations/
    spring.jmx.unique-names=true
    keycloak.realm=rutebanken
    server.port=8081
    server.admin.port=8080
    geocoder.max.retries=600
    keycloak.auth-server-url={{.Values.configMap.keycloakUrl}}
    spring.profiles.active=gcs-blobstore
    spring.datasource.url=jdbc:postgresql://localhost:5432/kakka
    tiamat.publish.export.cron.schedule=0+0+23+*+*+?
    tiamat.publish.localworkdir=/tmp/tiamat/publish
    quartz.enabled=true
    camel.springboot.name=kakka
    tiamat.export.max.retries=720
    tiamat.change.log.download.directory=/tmp/tiamat/changelog
    tiamat.administrative.units.update.directory=/tmp/tiamat/orgReg/adminUnits
    tiamat.neighbouring.countries.update.directory=/tmp/tiamat/countries
    kartverket.username=erlendnils1
    geocoder.place.type.whitelist=tettsteddel,bydel
    kartverket.download.directory=/tmp/tiamat/files/kartverket
    blobstore.gcs.project.id={{ .Values.configMap.blobstoreProjectId }}
    blobstore.gcs.container.name={{ .Values.configMap.gcsBlobstore }}
    blobstore.gcs.credential.path=/etc/kakka/credentials.json
    spring.datasource.username=kakka
    server.host=0.0.0.0
    server.admin.host=0.0.0.0
    tiamat.publish.export=Full,versionValidity=ALL&tariffZoneExportMode=ALL&topographicPlaceExportMode=ALL;CurrentAndFuture,versionValidity=CURRENT_FUTURE;Current,versionValidity=CURRENT;RailStations,versionValidity=CURRENT&stopPlaceType=RAIL_STATION;03_Oslo,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:03;11_Rogaland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:11;15_More og Romsdal,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:15;18_Nordland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:18;30_Viken,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:30;34_Innlandet,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:34;38_Vestfold_Telemark,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:38;42_Agder,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:42;46_Vestland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:46;54_Troms_Finnmark,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:54;50_Trondelag,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:50
    keycloak.bearer-only=true
    spring.main.sources=no.entur.kakka
    keycloak.resource=kakka
    #geocoder.autoStartup=true
    spring.main.allow-bean-definition-overriding=true

    ## TODO remove when keycloack spring sec adapter is fixed
    spring.main.allow-bean-definition-overriding=true

    ## Flyway configuration

    spring.flyway.baseline-description=<< Flyway Baseline >>
    spring.flyway.baseline-on-migrate=true
    spring.flyway.baseline-version=1
    spring.flyway.table=flyway_schema_history
    kartverket.admin.units.archive.filename=county/Basisdata_0000_Norge_25833_Fylker_SOSI.zip
    kartverket.admin.units.filename=Basisdata_0000_Norge_25833_Fylker_SOSI.sos
    spring.cloud.gcp.pubsub.project-id={{ .Values.configMap.pubsubProjectId }}
    spring.cloud.gcp.pubsub.credentials.location=file:/etc/kakka/credentials.json
    spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
    spring.cloud.gcp.pubsub.subscriber.executor-threads=30
    spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000
    entur.pubsub.subscriber.autocreate=false
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    #spring.flyway.enabled=true

    # Pelias config

    pelias.gtfs.stop.place.enabled= {{ .Values.configMap.pelias.gtfs }}
    pelias.gos.include=true
    pelias.place.boost= {{.Values.configMap.pelias.placeBoost}}
    pelias.stop.place.boost.config={{.Values.configMap.pelias.boostConfig}}
    pelias.gos.boost.factor= {{.Values.configMap.pelias.boostFactor }}
    pelias.address.boost={{.Values.configMap.pelias.addressBoost}}
    pelias.address.street.boost={{.Values.configMap.pelias.streetBoost}}
    pelias.gtfs.stopplace.boost={{.Values.configMap.pelias.stopPlaceBoost}}
    pelias.download.directory=/tmp/tiamat/pelias
    osmpoifilter.priority.default={{.Values.configMap.pelias.osmPoiFilterDefaultPriority}}
    tiamat.poi.update.directory=/tmp/tiamat/poi/update
    kakka.remote.kubernetes.namespace = {{.Values.env }}
    # Convert POIs directly from osm file
    osm.poi.update.enabled={{.Values.configMap.poiUpdateEnabled}}
    # Include POIs from tiamat netex file
    pelias.poi.include={{.Values.configMap.pelias.poiInclude}}
kind: ConfigMap
metadata:
  name: {{ template "kakka.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
