apiVersion: v1
data:
  application.properties: |-
    # Spring
    spring.profiles.active=gcs-blobstore
    spring.main.sources=no.entur.kakka
    spring.main.allow-bean-definition-overriding=true
    spring.datasource.url=jdbc:postgresql://localhost:5432/kakka
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=kakka
    spring.jmx.unique-names=true
    ## Flyway configuration
    spring.flyway.baseline-description=<< Flyway Baseline >>
    spring.flyway.baseline-on-migrate=true
    spring.flyway.baseline-version=1
    spring.flyway.table=flyway_schema_history
    #spring.flyway.enabled=true
    server.port=8080
    camel.springboot.name=kakka
    camel.servlet.mapping.context-path=/services/*
    camel.cluster.kubernetes.enabled=true
    camel.cluster.kubernetes.cluster-labels[app]=kakka
    camel.cluster.kubernetes.config-map-name=kakka-leaders

    # Tiamat
    tiamat.geocoder.export.autoStartup=true
    tiamat.poi.update.enabled=false
    tiamat.url={{ .Values.configMap.tiamatUrl }}
    tiamat.publish.export.cron.schedule={{.Values.configMap.tiamatExportSchedule}}
    tiamat.publish.export.cron.schedule.mid.day={{.Values.configMap.tiamatExportScheduleMidDay}}
    tiamat.publish.localworkdir=/tmp/tiamat/publish
    tiamat.geocoder.export.mid.day.autoStartup=true
    tiamat.geocoder.export.cron.schedule={{.Values.configMap.gecoderExportSchedule}}
    tiamat.geocoder.export.cron.schedule.mid.day={{.Values.configMap.gecoderExportScheduleMidDay}}
    tiamat.export.max.retries=720
    tiamat.export.retry.delay=25000
    tiamat.change.log.download.directory=/tmp/tiamat/changelog
    tiamat.administrative.units.update.directory=/tmp/tiamat/orgReg/adminUnits
    tiamat.neighbouring.countries.update.directory=/tmp/tiamat/countries
    tiamat.tariffzones.update.directory=/tmp/tiamat/tariffZones/
    tiamat.poi.update.directory=/tmp/tiamat/poi/update
    tiamat.exports.config.path=/etc/tiamat-config/tiamat-exports.yml
    tiamat.export.autoStartup = false
    kingu.export.autoStartup = true
    kingu.export.mid.day.autoStartup =true

    # Kartverket
    kartverket.download.directory=/tmp/tiamat/files/kartverket
    kartverket.admin.units.archive.filename=county/Basisdata_0000_Norge_25833_Fylker_SOSI.zip
    kartverket.admin.units.filename=Basisdata_0000_Norge_25833_Fylker_SOSI.sos
    # Downloads of Addresses from Kartverket are disabled because latest dataset does work with geocoder
    kartverket.address.download.autoStartup=false
    kartverket.addresses.download.cron.schedule=0+0+11+?+*+MON-FRI

    # Geocoder
    geocoder.max.retries=600
    geocoder.place.type.whitelist={{ .Values.configMap.pelias.geocoderPlaceTypeWhitelist }}
    #geocoder.autoStartup=true
    elasticsearch.scratch.deployment.name= {{ .Values.configMap.elasticsearchDeploymentName }}
    elasticsearch.scratch.upload.job.enabled={{ .Values.configMap.elasticsearchUploadJobEnabled }}
    elasticsearch.scratch.url={{ .Values.configMap.elasticsearchUrl }}
    kakka.remote.kubernetes.cronjob=es-data-upload-job
    kakka.remote.kubernetes.geocoder.cronjob={{ .Values.configMap.geoCoderCronJob }}
    # Pelias
    pelias.gtfs.stop.place.enabled= {{ .Values.configMap.pelias.gtfs }}
    pelias.gos.include=true
    pelias.place.boost= {{.Values.configMap.pelias.placeBoost}}
    pelias.stop.place.boost.config={{.Values.configMap.pelias.boostConfig}}
    pelias.gos.boost.factor= {{.Values.configMap.pelias.boostFactor }}
    pelias.address.boost={{.Values.configMap.pelias.addressBoost}}
    pelias.address.street.boost={{.Values.configMap.pelias.streetBoost}}
    pelias.gtfs.stopplace.boost={{.Values.configMap.pelias.stopPlaceBoost}}
    pelias.download.directory=/tmp/tiamat/pelias
    # Include POIs from netex file
    pelias.poi.include={{.Values.configMap.pelias.poiInclude}}
    pelias.poi.filter=custom_poi=festival

    # Blob store
    blobstore.gcs.project.id={{ .Values.configMap.blobstoreProjectId }}
    blobstore.gcs.target-project.id={{ .Values.configMap.blobstoreTargetProjectId }}
    blobstore.gcs.container.name={{ .Values.configMap.gcsBlobstore }}
    blobstore.gcs.target-container.name={{ .Values.configMap.gcsTargetBlobstore }}
    blobstore.gcs.source.container.name={{ .Values.configMap.gcsSourceBlobstore }}

    # OAuth2 Resource Server for Entur Partner tenant
    kakka.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri={{ .Values.configMap.auth0.partner.url }}
    kakka.oauth2.resourceserver.auth0.entur.partner.jwt.audience={{ .Values.configMap.auth0.ror.audience }}


    # OAuth2 Resource Server
    kakka.oauth2.resourceserver.auth0.ror.jwt.issuer-uri={{ .Values.configMap.auth0.ror.url }}
    kakka.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.configMap.auth0.ror.audience }}
    kakka.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # OAuth2 Client
    spring.security.oauth2.client.registration.kakka.authorization-grant-type=client_credentials
    spring.security.oauth2.client.registration.kakka.client-id={{ .Values.configMap.oauth2.client.id }}
    spring.security.oauth2.client.provider.kakka.token-uri={{ .Values.configMap.oauth2.client.url }}
    kakka.oauth2.client.audience={{ .Values.configMap.oauth2.client.audience }}

    # Authorization
    kakka.security.authorization-service=token-based
    kakka.security.role.assignment.extractor={{ .Values.configMap.roleAssignmentExtractor }}
    user.permission.rest.service.url={{ .Values.configMap.baba.service }}/services/organisations/users


    # PubSub
    kakka.pubsub.project.id = {{ .Values.configMap.pubsubProjectId }}
    spring.cloud.gcp.pubsub.project-id={{ .Values.configMap.pubsubProjectId }}
    spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
    spring.cloud.gcp.pubsub.subscriber.executor-threads=30
    spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000
    entur.pubsub.subscriber.autocreate=false

    pubsub.kakka.outbound.topic.nabu.job.event.topic=google-pubsub:{{ .Values.configMap.nabuPubsubProjectId }}:JobEventQueue
    pubsub.kakka.outbound.topic.kingu.netex.export=google-pubsub:{{ .Values.configMap.kinguPubsubProjectId }}:ror.kingu.outbound.topic.netex.export
    pubsub.kakka.inbound.subscription.kingu.netex.export=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.inbound.subscription.kingu.netex.export
    pubsub.kakka.outbound.topic.geocoder=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.outbound.topic.geocoder
    pubsub.kakka.inbound.subscription.geocoder=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.inbound.subscription.geocoder
    pubsub.kakka.inbound.subscription.tariff.zone.file.queue=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.inbound.subscription.tariff.zone.file.queue
    pubsub.kakka.outbound.topic.tariff.zone.file.queue=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.outbound.topic.tariff.zone.file.queue
    pubsub.kakka.inbound.subscription.geocoder.smoke.test=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.inbound.subscription.geocoder.smoke.test
    pubsub.kakka.inbound.subscription.es.build.job=google-pubsub:${kakka.pubsub.project.id}:ror.kakka.inbound.subscription.es.build.job



    # Actuator
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    #logging
    logging.level.com.conveyal=WARN



    # Other
    quartz.enabled=true
    organisations.api.url= {{ .Values.configMap.babaUrl }}
    osmpoifilter.priority.default={{.Values.configMap.pelias.osmPoiFilterDefaultPriority}}
    kakka.remote.kubernetes.namespace = {{ .Release.Namespace }}
    # Convert POIs directly from osm file
    osm.poi.update.enabled={{.Values.configMap.poiUpdateEnabled}}
    # TariffZone Import valid providers/authority
    tariff.zone.providers=AKT,ATB,BRA,FIN,HED,INN,KOL,MOR,NOR,OPP,OST,RUT,SKY,SOF,TRO,VKT,VOT
    fetch.osm.cron.schedule=0+0+19+?+*+MON-FRI
    kakka.slack.end.point=${SLACK_URL}

kind: ConfigMap
metadata:
  name: {{ template "kakka.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
