kakka:
  database: kakka
common:
  app: kakka
  shortname: kakka
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 80
    internalPort: 8080
  container:
    image: ${artifact.metadata.image}
    cpu: 2
    memory: 8500
    cpuLimit: 3
    memoryLimit: 9000
    probes:
      liveness:
        path: /actuator/health
      readiness:
        path: /actuator/health
    envFrom:
      - secretRef:
          name: ror-kakka-secrets
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: kakka-config
        name: application-config
  postgres:
    enabled: true
  configmap:
    data:
      JAVA_OPTIONS: -server -Xmx10G -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
        -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true