sql:
  instance: entur-ror-prod:europe-west1:kakka-db=tcp:5432

configMap:
  gcsBlobstore: ror-kakka-production
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  keycloakUrl: https://auth.entur.org/auth
  poiUpdateEnabled: true
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"airport\":{\"*\":2},\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10

ingress:
  enabled: true
  loadBalancerIP: 35.187.15.14
  domainName: -production.entur.io
monitoringEnabled: false

