sql:
  instance: neon-1287:europe-west1:kakka-db-1=tcp:5432

configMap:
  gcsBlobstore: marduk-production
  blobstoreProjectId: neon-1287
  pubsubProjectId: neon-1287
  keycloakUrl: https://auth.entur.org/auth
  poiUpdateEnabled: true
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"airport\":{\"*\":2},\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10

ingress:
  enabled: true
  loadBalancerIP: 35.205.233.237
  domainName: -production.entur.io
monitoringEnabled: false
rbac:
  enabled: true
