sql:
  instance: entur-ror-test:europe-west1:kakka-db-1=tcp:5432

configMap:
  gcsBlobstore: kakka-test
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: radon-1287
  keycloakUrl: https://kc-stage.devstage.entur.io/auth
  poiUpdateEnabled: false
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"airport\":{\"*\":2},\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10

ingress:
  enabled: true
  loadBalancerIP: 130.211.80.129
  domainName: -staging.staging.entur.io
monitoringEnabled: true
rbac:
  enabled: true
