sql:
  instance: entur-ror-dev:europe-west1:kakka-db-11=tcp:5432

configMap:
  gcsBlobstore: kakka-dev
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: carbon-1287
  keycloakUrl: https://kc-dev.devstage.entur.io/auth
  poiUpdateEnabled: true
  pelias:
    gtfs: true
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"airport\":{\"*\":2},\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10
    poiInclude: false

ingress:
  enabled: true
  loadBalancerIP: 35.205.170.68
  domainName: .dev.entur.io
monitoringEnabled: true
rbac:
  enabled: true
