sql:
  instance: entur-ror-test:europe-west1:kakka-db-1=tcp:5432

configMap:
  gcsBlobstore: kakka-test
  gcsTargetBlobstore: marduk-test
  blobstoreProjectId: entur-ror-test
  blobstoreTargetProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  keycloak:
    url:  https://kc-stage.devstage.entur.io/auth
  auth0:
    ror:
      url: https://ror-entur-staging.eu.auth0.com/
      audience: https://ror.api.staging.entur.io
  oauth2:
    client:
      id: kakka
      url: https://kc-stage.devstage.entur.io/auth/realms/rutebanken/protocol/openid-connect/token
      audience: account
  tiamatExportSchedule: 0+0+20+*+*+?
  gecoderExportSchedule: 0+0+04+*+*+?
  poiUpdateEnabled: true
  tiamatExport: Full,versionValidity=ALL&tariffZoneExportMode=ALL&topographicPlaceExportMode=ALL;CurrentAndFuture,versionValidity=CURRENT_FUTURE;Current,versionValidity=CURRENT;CurrentwithServiceFrame,versionValidity=CURRENT_FUTURE&serviceFrameExportMode=ALL&fareZoneExportMode=ALL&tariffZoneExportMode=ALL;RailStations,versionValidity=CURRENT&stopPlaceType=RAIL_STATION;03_Oslo,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:03;11_Rogaland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:11;15_More og Romsdal,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:15;18_Nordland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:18;30_Viken,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:30;34_Innlandet,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:34;38_Vestfold_Telemark,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:38;42_Agder,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:42;46_Vestland,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:46;54_Troms_Finnmark,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:54;50_Trondelag,versionValidity=CURRENT&countyReference=KVE:TopographicPlace:50
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10
    poiInclude: false
    geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse

ingress:
  enabled: true
  loadBalancerIP: 130.211.80.129
  domainName: .staging.entur.io
monitoringEnabled: true
rbac:
  enabled: true
