env: dev
sql:
  instance: ent-kakka-dev:europe-west1:kakka-db=tcp:5432

configMap:
  gcsBlobstore: kakka-dev
  gcsTargetBlobstore: marduk-dev
  blobstoreProjectId: entur-ror-dev
  blobstoreTargetProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  gcsSourceBlobstore: kingu-dev
  tiamatUrl: http://tiamat.dev.entur.internal:80
  tiamatExporterUrl: http://tiamat-exporter.dev.entur.internal:80
  babaUrl: http://baba.dev.entur.internal/services/organisations/
  auth0:
    ror:
      url: https://ror-entur-dev.eu.auth0.com/
      audience: https://ror.api.dev.entur.io
  oauth2:
    client:
      id: DWzqknzoqsSdT8AsMMjt9F3anaakb0nn
      url: https://ror-entur-dev.eu.auth0.com/oauth/token
      audience: https://ror.api.dev.entur.io
  tiamatExportSchedule: 0+0+02+*+*+?
  tiamatExportScheduleMidDay: 0+0+12+*+*+?
  gecoderExportSchedule: 0+0+04+*+*+?
  gecoderExportScheduleMidDay: 0+0+14+*+*+?
  poiUpdateEnabled: true
  tiamatExportConfig: environments/tiamat-exports-dev.yml
  slackSecret: ror-dev-slack-url
  pelias:
    gtfs: true
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10
    poiInclude: false
    geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse
  elasticsearchDeploymentName: es-scratch
  elasticsearchUploadJobEnabled: true
  elasticsearchUrl: http://es-scratch:9200
  geoCoderCronJob: geocoder-acceptance-tests-predeploy
ingress:
  domainName: -gcp2.dev.entur.io
monitoringEnabled: true

