env: prod
sql:
  instance: ent-kakka-prd:europe-west1:kakka-db=tcp:5432

configMap:
  gcsBlobstore: kakka-production
  gcsTargetBlobstore: marduk-production
  blobstoreProjectId: entur-ror-prod
  blobstoreTargetProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  nabuPubsubProjectId: entur-ror-prod
  gcsSourceBlobstore: kingu-production
  tiamatUrl: http://tiamat.prd.entur.internal:80
  tiamatExporterUrl: http://tiamat-exporter.prd.entur.internal:80
  babaUrl: http://baba.prd.entur.internal/services/organisations/
  auth0:
    ror:
      url: https://auth2.entur.org/
      audience: https://ror.api.entur.io
  oauth2:
    client:
      id: XBcxAAtgvAM9QtAs20ZFE77owIp9HUua
      url: https://auth2.entur.org/oauth/token
      audience: https://ror.api.entur.io
  tiamatExportSchedule: 0+0+23+*+*+?
  tiamatExportScheduleMidDay: 0+0+12+*+*+?
  gecoderExportSchedule: 0+0+22+*+*+?
  gecoderExportScheduleMidDay: 0+0+14+*+*+?
  poiUpdateEnabled: true
  tiamatExportConfig: environments/tiamat-exports-production.yml
  slackSecret: ror-prod-slack-url
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: "{\"defaultValue\":30, \"stopTypeFactors\":{\"busStation\":{\"*\":2},\"metroStation\":{\"*\":2},\"railStation\":{\"*\":2}}}"
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10
    poiInclude: false
    geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse
  elasticsearchDeploymentName: es-scratch
  elasticsearchUploadJobEnabled: true
  elasticsearchUrl: http://es-scratch:9200
  geoCoderCronJob: geocoder-acceptance-tests-predeploy

ingress:
  domainName: -gcp2.entur.io
monitoringEnabled: false

