env: test
sql:
  instance: ent-kakka-tst:europe-west1:kakka-db=tcp:5432

configMap:
  gcsBlobstore: ror-kakka-test
  gcsTargetBlobstore: marduk-test
  blobstoreProjectId: ent-kakka-tst
  blobstoreTargetProjectId: entur-ror-test
  pubsubProjectId: ent-kakka-tst
  kinguPubsubProjectId: ent-kingu-tst
  nabuPubsubProjectId: ent-nabu-tst
  gcsSourceBlobstore: ror-kingu-test
  tiamatUrl: http://tiamat.tst.entur.internal:80
  tiamatExporterUrl: http://tiamat-exporter.tst.entur.internal:80
  babaUrl: http://baba.tst.entur.internal/services/organisations/
  auth0:
    ror:
      url: https://ror-entur-staging.eu.auth0.com/
      audience: https://ror.api.staging.entur.io
    partner:
        url: https://partner.staging.entur.org/
  oauth2:
    client:
      id: 8qtEWzdSAaH7auRqBwSdRzjOdjMVNVlw
      url: https://ror-entur-staging.eu.auth0.com/oauth/token
      audience: https://ror.api.staging.entur.io
  tiamatExportSchedule: 0+0+02+*+*+?
  tiamatExportScheduleMidDay: 0+0+12+*+*+?
  gecoderExportSchedule: 0+0+04+*+*+?
  gecoderExportScheduleMidDay: 0+0+14+*+*+?
  poiUpdateEnabled: true
  tiamatExportConfig: env/tiamat-exports-kub-ent-dev.yml
  slackSecret: ror-staging-slack-url
  pelias:
    gtfs: false
    placeBoost: 40
    boostConfig: '{"defaultValue":30, "stopTypeFactors":{"busStation":{"*":2},"metroStation":{"*":2},"railStation":{"*":2}}}'
    boostFactor: 10
    addressBoost: 20
    streetBoost: 20
    stopPlaceBoost: 40
    osmPoiFilterDefaultPriority: 10
    poiInclude: false
    geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse
  elasticsearchDeploymentName: es-scratch
  elasticsearchUploadJobEnabled: true
  elasticsearchUrl: http://es-scratch:9200
  geoCoderCronJob: geocoder-acceptance-tests-predeploy

ingress:
  domainName: -gcp2.staging.entur.io
monitoringEnabled: true

cronjobTiamatExportStatus:
  environmentVar:
    bucketPath: gs://marduk-test/tiamat/
