env: test

configMap:
  gcsBlobstore: ror-kakka-test
  gcsTargetBlobstore: marduk-test
  blobstoreProjectId: ent-kakka-tst
  blobstoreTargetProjectId: entur-ror-test
  pubsubProjectId: ent-kakka-tst
  kinguPubsubProjectId: ent-kingu-tst
  nabuPubsubProjectId: ent-nabu-tst
  gcsSourceBlobstore: ror-kingu-test
  tiamatUrl: http://tiamat.tst.entur.internal:80
  tiamatExporterUrl: http://tiamat-exporter.tst.entur.internal:80
  babaUrl: http://baba.tst.entur.internal/services/organisations/
  auth0:
    partner:
      url: https://partner.staging.entur.org/
      audience: https://api.staging.entur.io
  oauth2:
    client:
      url: https://internal.staging.entur.org/oauth/token
      audience: https://api.staging.entur.io
  baba:
    service: http://baba.tst.entur.internal

  roleAssignmentExtractor: baba

  tiamatExportSchedule: 0+0+02+*+*+?
  tiamatExportScheduleMidDay: 0+0+12+*+*+?
  geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse
  tiamatExportConfig: env/tiamat-exports-kub-ent-dev.yml
  slackSecret: ror-staging-slack-url

ingress:
  domainName: -gcp2.staging.entur.io
monitoringEnabled: true

cronjobTiamatExportStatus:
  environmentVar:
    bucketPath: gs://marduk-test/tiamat/
