env: dev

configMap:
  gcsBlobstore: ror-kakka-dev
  gcsTargetBlobstore: marduk-dev
  blobstoreProjectId: ent-kakka-dev
  blobstoreTargetProjectId: entur-ror-dev
  pubsubProjectId: ent-kakka-dev
  kinguPubsubProjectId: ent-kingu-dev
  nabuPubsubProjectId: ent-nabu-dev
  gcsSourceBlobstore: ror-kingu-dev
  tiamatUrl: http://tiamat.dev.entur.internal:80
  tiamatExporterUrl: http://tiamat-exporter.dev.entur.internal:80
  babaUrl: http://baba.dev.entur.internal/services/organisations/
  auth0:
    partner:
      url: https://partner.dev.entur.org/
      audience: https://api.dev.entur.io
  oauth2:
    client:
      url: https://internal.dev.entur.org/oauth/token
      audience: https://api.dev.entur.io
  baba:
    service: http://baba.dev.entur.internal
  roleAssignmentExtractor: baba
  tiamatExportSchedule: 0+0+02+*+*+?
  tiamatExportScheduleMidDay: 0+0+12+*+*+?
  geocoderPlaceTypeWhitelist: tettsteddel,bydel,by,tettsted,tettbebyggelse
  tiamatExportConfig: env/tiamat-exports-kub-ent-dev.yml
  slackSecret: ror-dev-slack-url
ingress:
  domainName: -gcp2.dev.entur.io
monitoringEnabled: true

cronjobTiamatExportStatus:
  environmentVar:
    bucketPath: gs://marduk-dev/tiamat/
