gcp_project = "entur-ror-dev"
cloudsql_project = "entur-ror-dev"
pubsub_project = "entur-ror-dev"
storage_project = "entur-ror-dev"
kube_namespace = "dev"
service_account_bucket_role = "roles/storage.objectAdmin"
kakka_storage_bucket = "kakka-dev"
