gcp_project = "entur-ror-dev"
cloudsql_project = "entur-ror-dev"
pubsub_project = "entur-ror-dev"
kube_namespace = "dev"
service_account_bucket_role = "roles/storage.objectAdmin"
kakka_storage_bucket = "kakka-dev"
kingu_storage_bucket = "kingu-dev"
kakka_target_storage_bucket = "marduk-dev"
