gcp_project = "entur-ror-prod"
cloudsql_project = "entur-ror-prod"
pubsub_project = "neon-1287"
storage_project = "neon-1287"
kube_namespace = "production"
service_account_bucket_role = "roles/storage.objectAdmin"
kakka_storage_bucket = "marduk-production"