gcp_project = "entur-ror-test"
cloudsql_project = "entur-ror-test"
pubsub_project = "radon-1287"
storage_project = "radon-1287"
kube_namespace = "staging"
service_account_bucket_role = "roles/storage.objectAdmin"
kakka_storage_bucket = "marduk-stage"