apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "kakka.labels" . | indent 4 }}
  name: es-data-upload-job
  namespace: kakka
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-b
          containers:
            - name: es-data-upload-job
              image: eu.gcr.io/entur-system-1287/es-data-uploader:0.0.14
              imagePullPolicy: Always
              env:
                    - name: TZ
                      value: Europe/Oslo
                    - name: CLOUDSDK_CORE_PROJECT
                      value: {{.Values.esData.gcpProject}}
                    - name: GCS_UPLOAD_PATH
                      value: {{.Values.esData.gcsBucket}}
                    - name: MIN_FILE_SIZE
                      value: "1000"
                    - name: K8S_NAMESPACE
                      value: dev
                    - name: SLACK_URL
                      valueFrom:
                        secretKeyRef:
                          key: slack-url
                          name: {{.Values.esData.slackUrl}}
              resources:
                limits:
                  cpu: 900m
                  memory: 2550Mi
                requests:
                  cpu: 100m
                  memory: 1000Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                      - ALL
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /work/data
                  name: es-scratch-data
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          serviceAccountName: application
          terminationGracePeriodSeconds: 30
          volumes:
            - name: es-scratch-data
              gcePersistentDisk:
                pdName: ror-es-scratch-disk
                fsType: ext4
      ttlSecondsAfterFinished: 100
  schedule: 0 0 1 1 0
  successfulJobsHistoryLimit: 1
  suspend: true