apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-scratch
    team: ror
    slack: talk-ror
    type: geocoder
  name: es-scratch
  namespace: kakka
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: es-scratch
  sessionAffinity: None
  type: ClusterIP
