apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    {{- include "es-upload.labels" . | indent 4 }}
  name: es-upload-job
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                    - europe-west1-b
          containers:
          - env:
            - name: TZ
              value: Europe/Oslo
            - name: CLOUDSDK_CORE_PROJECT
              value: {{ .Values.esUploadCronJob.gcp.projectId }}
            - name: GCS_UPLOAD_PATH
              value: gs://{{ .Values.esUploadCronJob.gcp.bucketName }}/es-data/
            - name: MIN_FILE_SIZE
              value: "1000"
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  key: slack-url
                  name: {{ .Values.esUploadCronJob.environment.slackUrl }}
            - name: RUN_ACCEPTANCE_TESTS
              value: "false"
            - name: RESTART_PELIAS
              value: "false"
            image: eu.gcr.io/entur-system-1287/es-data-uploader:0.0.14
            imagePullPolicy: Always
            name: es-build-job
            resources:
              limits:
                cpu: 900m
                memory: 2550Mi
              requests:
                cpu: 100m
                memory: 1000Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            volumeMounts:
            - mountPath: /work/data
              name: es-scratch-data
            - mountPath: /etc/es-build-job/credentials.json
              name: es-build-job-key
              readOnly: true
              subPath: credentials.json
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          serviceAccountName: es-build-job-service-account
          terminationGracePeriodSeconds: 30
          volumes:
          - gcePersistentDisk:
              fsType: ext4
              pdName: ror-es-scratch-disk
            name: es-scratch-data
          - name: es-build-job-key
            secret:
              defaultMode: 420
              secretName: ror-es-build-job-sa-key
  schedule: 0 0 1 1 0
  successfulJobsHistoryLimit: 1
  suspend: true
status: {}
