cloudsql_project = "ent-kakka-prd"
pubsub_project="ent-kakka-prd"
kingu_pub_sub_project ="ent-kingu-prd"
nabu_job_event_pubsub_project="ent-nabu-prd"
service_account="serviceAccount:application@ent-kakka-prd.iam.gserviceaccount.com"
kingu_storage_bucket="ror-kingu-production"
