cloudsql_project = "ent-kakka-tst"
pubsub_project="ent-kakka-tst"
storage_project="ent-kakka-tst"
kingu_pub_sub_project ="ent-kingu-tst"
nabu_job_event_pubsub_project="ent-nabu-tst"
service_account="serviceAccount:application@ent-kakka-tst.iam.gserviceaccount.com"
kingu_storage_bucket="ror-kingu-test"
bucket_instance_suffix="test"
