name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  maven-verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.7+9
          distribution: liberica
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - run: mvn verify
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: target/*.jar
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.ENTUR_SONAR_PASSWORD }}
          SONAR_PROJECT_NAME: ${{ github.event.repository.name }}
          SONAR_PROJECT_KEY: entur_${{ github.event.repository.name }}
        run: |
          mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify \
                  org.jacoco:jacoco-maven-plugin:report sonar:sonar \
                  -Dmaven.main.skip \
                  -DskipTests \
                  -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                  -Dsonar.organization=enturas-github \
                  -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                  -Dsonar.host.url=https://sonarcloud.io \
                  -Dsonar.token=${SONAR_TOKEN}
  docker-lint:
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
     ignore: "DL3018"

  docker-build:
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1

  docker-scan:
    needs: [ docker-build ]
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.docker-build.outputs.image_artifact }}